# Generated by Django 4.1.3 on 2023-07-31 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="activity",
            fields=[
                (
                    "activity_ID",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("activity_name", models.CharField(max_length=255)),
                ("activity_Date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="add_ativity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_name", models.CharField(max_length=255)),
                ("activity_Date", models.CharField(max_length=50)),
                ("activity_data", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="add_data_all",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_user_name", models.CharField(max_length=255)),
                ("add_Id_studen", models.CharField(max_length=255)),
                ("add_f_name", models.CharField(max_length=255)),
                ("add_l_name", models.CharField(max_length=255)),
                ("add_fieldstudy", models.CharField(max_length=255)),
                ("add_activity", models.CharField(max_length=255)),
                ("add_id_activity", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="crtateuser",
            fields=[
                (
                    "ID_studen",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("f_name", models.CharField(max_length=50)),
                ("l_name", models.CharField(max_length=50)),
                ("sa_name", models.CharField(max_length=50)),
                ("Confirm_Password", models.CharField(max_length=50)),
                ("Password", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "crtateuser",
                "verbose_name_plural": "crtateusers",
            },
        ),
        migrations.CreateModel(
            name="LOGIN",
            fields=[
                (
                    "IDname",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("fname", models.CharField(max_length=50)),
                ("lname", models.CharField(max_length=50)),
                ("saka", models.CharField(max_length=50)),
            ],
            options={"verbose_name": "LOGIN", "verbose_name_plural": "LOGIN",},
        ),
        migrations.CreateModel(
            name="post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("news", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="study_group",
            fields=[
                (
                    "study_ID",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("study_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="test9",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strtest1", models.CharField(max_length=50)),
                ("strtest2", models.CharField(max_length=50)),
                ("strtest3", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idstuden", models.CharField(max_length=10)),
                ("fieldstudy", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="add_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_name", models.CharField(max_length=255)),
                ("activity", models.CharField(max_length=255)),
                ("Date", models.DateTimeField(auto_now=True)),
            ],
            options={"unique_together": {("id_name", "activity")},},
        ),
    ]
