# Generated by Django 4.1.3 on 2023-07-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="post",),
    ]
